[package]
name = "macros"
description = "A package macros for deriving ..."
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "~1"
quote = "~1"
syn = "~2"
